lib: [
  "_build/install/default/lib/ent-ocaml-ppx/META"
  "_build/install/default/lib/ent-ocaml-ppx/dune-package"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.a"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cma"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cmi"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cmt"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cmx"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cmxa"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.ml"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx__Ppx_ent_ocaml.cmi"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx__Ppx_ent_ocaml.cmt"
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx__Ppx_ent_ocaml.cmx"
  "_build/install/default/lib/ent-ocaml-ppx/opam"
  "_build/install/default/lib/ent-ocaml-ppx/ppx_ent_ocaml.ml"
]
libexec: [
  "_build/install/default/lib/ent-ocaml-ppx/ent_ocaml_ppx.cmxs"
  "_build/install/default/lib/ent-ocaml-ppx/ppx.exe"
]
doc: [
  "_build/install/default/doc/ent-ocaml-ppx/README.md"
]
